version: '3.8'

services:
  app:
    container_name: app-tasks
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
